name: Publish Mod

# Run when a new release is... released
on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v3.1
        with:
          namespace: MWG # the thunderstore 'team' to publish under
          description: Beta version of Morningwood Gaming Valhalla Modded. Used only for testing! 
          token: ${{ secrets.YOUR_TOKEN_NAME }}
          name: MWG-MWG_Valhalla # the name of the package
          version: ${{ github.event.release.tag_name }} # Use the tag as the package version
          community: Valheim
