name: Merge Releaser

# Run when a new release is... released
on:
  pull_request:
    types: [closed]
    branches:    
      - main
jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'manifest.json'
          prop_path: 'version_number'
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          changelog_file: README.md
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.version.outputs.prop}} 
          release_name: ${{steps.version.outputs.prop}} 
          draft: false
          prerelease: false
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
